version: 2
requirements:
  signed_off_by:
    required: false
group_defaults:
  approve_by_comment:
    approve_regex: '^(:shipit:|:\+1:|LGTM|Approved|Looks\s+Good|Seems\s+Good)/i'
    reject_regex: '^(Rejected|:-1:)/i'
  reset_on_push:
    enabled: true
groups:
  -reviewers:
    required: 1
    users:
      - Idrinth
      - w20k
    conditions:
      branches:
        - master
